### ISSUE TITLE
适配其他模型

### ISSUE THREAD

**Issue by tkone2018** [jianghoucheng/AlphaEdit#1]
请问可以适配其他的模型吗，比如qwen

**Comment by MangoKiller** [comment]
可以的，绝大部分主流的LLM都是可以适配的。如果有兴趣欢迎邮件和我们交流！

**Comment by MangoKiller** [comment]
> 请问可以适配其他的模型吗，比如qwen

可以的，绝大部分主流的LLM都是可以适配的。如果有兴趣欢迎邮件和我们交流！
