### ISSUE TITLE
Some question about experiments result in papaer

### ISSUE THREAD

**Issue by Darknessrky** [jianghoucheng/AlphaEdit#8]
Excellent paper by the way, but I had a question when I read it.

-------
For COUNTERFACT's Specificity
-------
Paper mentioned in A.2.2,
![image](https://github.com/user-attachments/assets/d8c32ea5-b2f8-4925-8e8c-309e0c65b48f)
If the '>' should be '<' ?
And to measure Specificity need edited target output  ![image](https://github.com/user-attachments/assets/4842e963-385f-4a45-a182-1b62c752d60c) and the model’s original output  ![image](https://github.com/user-attachments/assets/c2b617f4-7b15-4da3-a66f-a9716b51a3b1), so how can you calculate pre-edited model's Specificity? What is ![image](https://github.com/user-attachments/assets/4842e963-385f-4a45-a182-1b62c752d60c) for  pre-edited model?

 -------
For ZSRE's Specificity
-------
And why your method's Specificity can better than a pre-edited method? It's kind of counterintuitive for me.
![image](https://github.com/user-attachments/assets/6ae2d91a-cf78-4c2b-8202-6e0187740c39)

**Comment by jianghoucheng** [comment]
Thank you for your recognition of our work.
Firstly, the formula for COUNTERFACT's Specificity is indeed '<'. We made a mistake here. Thank you for pointing out the problem and we will correct this error.
Secondly, regarding specificity, we completely follow the evaluation metrics in the ROME and MEMIT articles. In the counterfact dataset, there is a ground truth and a new target that needs to be updated. Specificity compares the probability of the current output with that of the ground truth. Therefore, the specificity of the pre-edited model also compares the probability of the current output with that of the ground truth.
Finally, as for the situation where specificity is greater than that of the pre-edited model, we were also curious about this issue during the experiment. Our explanation is that there may be cases where the target answers of samples are the same in the ZSRE dataset. Therefore, when calculating specificity based on neighboring samples, there may be a situation where the target is the same as that of a previously edited sample, which increases the probability of this neighbor answering correctly. Of course, this explanation has not been experimentally verified by us and is for reference only. If you have a better understanding, you can also discuss it with us.

**Comment by Darknessrky** [comment]
Thanks for your reply, my question has been clearly answered
