### ISSUE TITLE
Implementation of MEND method editing Llama3-8B-Instruct

### ISSUE THREAD

**Issue by asdfo123** [jianghoucheng/AlphaEdit#9]
Thanks for your great work!
Currently I'm reproducing your experiments, but I encountered issues when I'm trying to implement MEND to LLama3-8B-Instruct. Could you please provide details about MEND methods?

**Comment by asdfo123** [comment]
Hello，Recently I tried to use MEND editing Llama3-8B, but it seems that the code of MEND in AlphaEdit repository doesn't support  Llama3-8B. Do you have any advice about reproducing?

**Comment by jianghoucheng** [comment]
We have developed a new codebase that adapts hypernetwork methods, including MEND and MALMEN, to other large models such as LLaMA3 and gemma2, as well as other baselines. This is part of our latest work on improving the hypernetwork series of methods, which will be released next month. We will inform you with the specific project link at that time, and we hope for your understanding.

**Comment by asdfo123** [comment]
> We have developed a new codebase that adapts hypernetwork methods, including MEND and MALMEN, to other large models such as LLaMA3 and gemma2, as well as other baselines. This is part of our latest work on improving the hypernetwork series of methods, which will be released next month. We will inform you with the specific project link at that time, and we hope for your understanding.

Great to hear that! Looking forward to your new work!
